name: GitHub Pages

on:
  # https://github.com/actions/deploy-pages/issues/418#issuecomment-4883549401
  workflow_dispatch:
  push:
    tags:
      - v*

permissions: read-all

jobs:
  gh-pages:
    name: Publish to GitHub Pages
    runs-on: ubuntu-slim
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: false
      - run: uv run --only-dev zensical build -s
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: rm -rf site/assets/images/favicon.png site/assets/stylesheets/classic
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - id: deployment
        uses: actions/deploy-pages@v5
